### ISSUE TITLE
Logging user write permissions conflict with RotatingFileHandler

### ISSUE THREAD

**Issue by jurvtk** [eStation2/eStation2#10]
There is a conflict within the python logging system concerning the user write permissions when using the RotatingFileHandler. When a call is made from the browser to WebPy through Apache, the user www-data is the active user. If the call runs functionality where the logging system is issued, the user www-data does not have the right permissions.

For example when the service geteumetcast is running it is issued by the user "esuser" which the becomes the owner of the rotating log files apps.acquisition.geteumetcast.log.x. Now when the user www-data calls the query querydb.getdataacquisitions(echo=False) in \database\querydb.py a sub call to geteumetcastinfo(row.datasourceid) in \apps\acquisition\geteumetcast.py is issued where the logger tries to write in the file apps.acquisition.get_eumetcast.log.x as the user www-data and thus goes in error because of missing permissions.

The logging system does not give the possibility to change the permissions to the files it creates! Maybe the solution could be to create a logging group containing the users www-data and esuser and assign this logging group as the owner of the log directory.

**Comment by mclerici** [comment]
The same problem appears for the log file of the database: a solution should be found to have automatically all files in log created with permission 777

**Comment by mclerici** [comment]
Consider using ACL default permission for all files in /log dir, to be set by using the command (in postinst):

setfacl -d -m user:www-data:rwx /srv/www/eStation2/log

to be tested (to clarify how it works with POSIX permissions)

**Comment by mclerici** [comment]
Changing umask to 000 (in a shell) causes all files (including logs) to be generated with permissions 666.

**Comment by mclerici** [comment]
The definition: 

umask 0000

is added to /etc/bash.bashrc (on mesa-proc, FTTB). It seems to apply also www-data user.

**Comment by mclerici** [comment]
This is now ok.
