### ISSUE TITLE
Get Internet Sleep Time

### ISSUE THREAD

**Issue by taxmanyana** [eStation2/eStation2#29]
Hello,

May I suggest we include an option to implement sleep time for each product in the Get Internet. This is because some products are more frequent than others (e.g some are 15mins and some 10 days).
For example, If the source of the 10 day product has thousand of files (e.g.GSOD) then if its sleep time is too small then it will delay the processing of the more frequent products.
Thanks,

Thembani

**Comment by mclerici** [comment]
Done, by using the 'pull_frequency' of the internet_sources' table and the info in the pickle .info
