### ISSUE TITLE
Field exclude_files_expression in internet table

### ISSUE THREAD

**Issue by mclerici** [eStation2/eStation2#50]
To be renamed as 'files_filter_expression' and to be used for identifying files in /data/ingest.
The 'include_files_expression' is not suitable for such an usage, as it might be a template (%Y%j%d)
Furthermore, with the new approaches, it has no usage as exclude.

**Comment by jurvtk** [comment]
Changed column name from exclude_files_expression to files_filter_expression on vm19 and mesa-proc.
