### ISSUE TITLE
Web Interface Internal Server error

### ISSUE THREAD

**Issue by ikwilliams** [eStation2/eStation2#64]
eStation 2.0 was succesfully installed on Dell Inspiron 15R laptop with database and estation apps installed. Unfortunately the web interface worked fine until the system was rebooted. it now reports internal server error after restart. 

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.

Apache/2.4.12 (Ubuntu) Server at localhost Port 80

any help??

**Comment by mclerici** [comment]
Dear Ignatius

first hint would be to look at (and send to us, if you like) the log file: /var/log/apache2/error.log
I suspect it is a permission error. Consider also we have a new release (include image visualisation) and the updated DB, we can share early next week !
Regards
Marco

**Comment by ikwilliams** [comment]
please find attached the error.log

On Thu, Apr 16, 2015 at 6:54 PM, mclerici <notifications@github.com> wrote:

> Dear Ignatius
>
> first hint would be to look at (and send to us, if you like) the log file:
> /var/log/apache2/error.log
> I suspect it is a permission error. Consider also we have a new release
> (include image visualisation) and the updated DB, we can share early next
> week !
> Regards
> Marco
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/eStation2/eStation2/issues/64#issuecomment-93801743>.
>



-- 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
I.K. Williams
Systems Administrator,
ECOWAS Coastal & Marine Resources Management Centre
Monitoring for Environment & Security in Africa (MESA)
University of Ghana
P.O. Box LG 99, Legon. GHANA
Mobile: +233(0)243330445
email: idoublegy@gmail.com
ikwekuwilliams@gmail.com
Office Location/Courier Delivery:
ARPIS Building, JKM Hodasi Street

**Comment by mclerici** [comment]
Hi Ignatius

yes, permissions: please change by doing:

sudo chmod -R 777 /tmp/eStation2

I'll send you next week the rc.local to replace the existing one (it does
the job at boot)
Marco

**Comment by ikwilliams** [comment]
Yes, that would be appreciated and i wouldn't have to reset permissions at
boot (on restart) each time.

Dual booting with windows 8.1 seems to be working fine also without any
issues
